// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1.amqp.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Delivery struct {
	CreatedAt            string   `protobuf:"bytes,1,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Retry                int32    `protobuf:"varint,2,opt,name=retry,proto3" json:"retry,omitempty"`
	Message              *any.Any `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Delivery) Reset()         { *m = Delivery{} }
func (m *Delivery) String() string { return proto.CompactTextString(m) }
func (*Delivery) ProtoMessage()    {}
func (*Delivery) Descriptor() ([]byte, []int) {
	return fileDescriptor_55eb7a5301ad84b1, []int{0}
}

func (m *Delivery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Delivery.Unmarshal(m, b)
}
func (m *Delivery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Delivery.Marshal(b, m, deterministic)
}
func (m *Delivery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Delivery.Merge(m, src)
}
func (m *Delivery) XXX_Size() int {
	return xxx_messageInfo_Delivery.Size(m)
}
func (m *Delivery) XXX_DiscardUnknown() {
	xxx_messageInfo_Delivery.DiscardUnknown(m)
}

var xxx_messageInfo_Delivery proto.InternalMessageInfo

func (m *Delivery) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Delivery) GetRetry() int32 {
	if m != nil {
		return m.Retry
	}
	return 0
}

func (m *Delivery) GetMessage() *any.Any {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*Delivery)(nil), "api.Delivery")
}

func init() { proto.RegisterFile("v1.amqp.proto", fileDescriptor_55eb7a5301ad84b1) }

var fileDescriptor_55eb7a5301ad84b1 = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x33, 0xd4, 0x4b,
	0xcc, 0x2d, 0x2c, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x94, 0x92,
	0x4c, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x0b, 0x25, 0x95, 0xa6, 0xe9, 0x27, 0xe6, 0x55,
	0x42, 0xe4, 0x95, 0xf2, 0xb8, 0x38, 0x5c, 0x52, 0x73, 0x32, 0xcb, 0x52, 0x8b, 0x2a, 0x85, 0x64,
	0xb8, 0x38, 0x93, 0x8b, 0x52, 0x13, 0x4b, 0x52, 0x53, 0x1c, 0x4b, 0x24, 0x18, 0x15, 0x18, 0x35,
	0x38, 0x83, 0x10, 0x02, 0x42, 0x22, 0x5c, 0xac, 0x45, 0xa9, 0x25, 0x45, 0x95, 0x12, 0x4c, 0x0a,
	0x8c, 0x1a, 0xac, 0x41, 0x10, 0x8e, 0x90, 0x1e, 0x17, 0x7b, 0x6e, 0x6a, 0x71, 0x71, 0x62, 0x7a,
	0xaa, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0xb7, 0x91, 0x88, 0x1e, 0xc4, 0x32, 0x3d, 0x98, 0x65, 0x7a,
	0x8e, 0x79, 0x95, 0x41, 0x30, 0x45, 0x49, 0x6c, 0x60, 0x61, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x5f, 0x19, 0x92, 0x27, 0xa7, 0x00, 0x00, 0x00,
}
