// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1.identify.newfile.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IdentifyNewFile struct {
	// when this was created
	CreatedAt string `protobuf:"bytes,1,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	// media object
	Media *Media `protobuf:"bytes,2,opt,name=media,proto3" json:"media,omitempty"`
	// key of the file
	Key string `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	// quality of the file
	Quality              string   `protobuf:"bytes,4,opt,name=quality,proto3" json:"quality,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdentifyNewFile) Reset()         { *m = IdentifyNewFile{} }
func (m *IdentifyNewFile) String() string { return proto.CompactTextString(m) }
func (*IdentifyNewFile) ProtoMessage()    {}
func (*IdentifyNewFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_f727e4443d5a0d91, []int{0}
}

func (m *IdentifyNewFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdentifyNewFile.Unmarshal(m, b)
}
func (m *IdentifyNewFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdentifyNewFile.Marshal(b, m, deterministic)
}
func (m *IdentifyNewFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdentifyNewFile.Merge(m, src)
}
func (m *IdentifyNewFile) XXX_Size() int {
	return xxx_messageInfo_IdentifyNewFile.Size(m)
}
func (m *IdentifyNewFile) XXX_DiscardUnknown() {
	xxx_messageInfo_IdentifyNewFile.DiscardUnknown(m)
}

var xxx_messageInfo_IdentifyNewFile proto.InternalMessageInfo

func (m *IdentifyNewFile) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *IdentifyNewFile) GetMedia() *Media {
	if m != nil {
		return m.Media
	}
	return nil
}

func (m *IdentifyNewFile) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *IdentifyNewFile) GetQuality() string {
	if m != nil {
		return m.Quality
	}
	return ""
}

func init() {
	proto.RegisterType((*IdentifyNewFile)(nil), "api.IdentifyNewFile")
}

func init() { proto.RegisterFile("v1.identify.newfile.proto", fileDescriptor_f727e4443d5a0d91) }

var fileDescriptor_f727e4443d5a0d91 = []byte{
	// 163 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x33, 0xd4, 0xcb,
	0x4c, 0x49, 0xcd, 0x2b, 0xc9, 0x4c, 0xab, 0xd4, 0xcb, 0x4b, 0x2d, 0x4f, 0xcb, 0xcc, 0x49, 0xd5,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x94, 0xe2, 0x2b, 0x33, 0xd4, 0xcb,
	0x4d, 0x4d, 0xc9, 0x4c, 0x84, 0x08, 0x2a, 0xd5, 0x72, 0xf1, 0x7b, 0x42, 0x95, 0xfb, 0xa5, 0x96,
	0xbb, 0x65, 0xe6, 0xa4, 0x0a, 0xc9, 0x70, 0x71, 0x26, 0x17, 0xa5, 0x26, 0x96, 0xa4, 0xa6, 0x38,
	0x96, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x21, 0x04, 0x84, 0x14, 0xb8, 0x58, 0xc1, 0xfa,
	0x25, 0x98, 0x14, 0x18, 0x35, 0xb8, 0x8d, 0xb8, 0xf4, 0x12, 0x0b, 0x32, 0xf5, 0x7c, 0x41, 0x22,
	0x41, 0x10, 0x09, 0x21, 0x01, 0x2e, 0xe6, 0xec, 0xd4, 0x4a, 0x09, 0x66, 0xb0, 0x4e, 0x10, 0x53,
	0x48, 0x82, 0x8b, 0xbd, 0xb0, 0x34, 0x31, 0x27, 0xb3, 0xa4, 0x52, 0x82, 0x05, 0x2c, 0x0a, 0xe3,
	0x26, 0xb1, 0x81, 0x5d, 0x61, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x52, 0xd7, 0xe6, 0xce, 0xb7,
	0x00, 0x00, 0x00,
}
