// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1.telemetry.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Status is the status of this media
type TelemetryStatusEntry int32

const (
	// 0 isn't sent over the write in a lot of proto implementations, but is required to be
	// set in an enum, so we just throw this away here
	TelemetryStatusEntry_EMPTY_4     TelemetryStatusEntry = 0
	TelemetryStatusEntry_QUEUED      TelemetryStatusEntry = 1
	TelemetryStatusEntry_DOWNLOADING TelemetryStatusEntry = 2
	TelemetryStatusEntry_CONVERTING  TelemetryStatusEntry = 3
	TelemetryStatusEntry_UPLOADING   TelemetryStatusEntry = 4
	TelemetryStatusEntry_DEPLOYED    TelemetryStatusEntry = 5
	TelemetryStatusEntry_ERRORED     TelemetryStatusEntry = 6
)

var TelemetryStatusEntry_name = map[int32]string{
	0: "EMPTY_4",
	1: "QUEUED",
	2: "DOWNLOADING",
	3: "CONVERTING",
	4: "UPLOADING",
	5: "DEPLOYED",
	6: "ERRORED",
}

var TelemetryStatusEntry_value = map[string]int32{
	"EMPTY_4":     0,
	"QUEUED":      1,
	"DOWNLOADING": 2,
	"CONVERTING":  3,
	"UPLOADING":   4,
	"DEPLOYED":    5,
	"ERRORED":     6,
}

func (x TelemetryStatusEntry) String() string {
	return proto.EnumName(TelemetryStatusEntry_name, int32(x))
}

func (TelemetryStatusEntry) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c6a92aaa48c84f56, []int{0}
}

type TelemetryError struct {
	// id for this error
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// mediaId this error correlates too
	MediaId string `protobuf:"bytes,2,opt,name=mediaId,proto3" json:"mediaId,omitempty"`
	// error message
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TelemetryError) Reset()         { *m = TelemetryError{} }
func (m *TelemetryError) String() string { return proto.CompactTextString(m) }
func (*TelemetryError) ProtoMessage()    {}
func (*TelemetryError) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a92aaa48c84f56, []int{0}
}

func (m *TelemetryError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TelemetryError.Unmarshal(m, b)
}
func (m *TelemetryError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TelemetryError.Marshal(b, m, deterministic)
}
func (m *TelemetryError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TelemetryError.Merge(m, src)
}
func (m *TelemetryError) XXX_Size() int {
	return xxx_messageInfo_TelemetryError.Size(m)
}
func (m *TelemetryError) XXX_DiscardUnknown() {
	xxx_messageInfo_TelemetryError.DiscardUnknown(m)
}

var xxx_messageInfo_TelemetryError proto.InternalMessageInfo

func (m *TelemetryError) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TelemetryError) GetMediaId() string {
	if m != nil {
		return m.MediaId
	}
	return ""
}

func (m *TelemetryError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type TelemetryStatus struct {
	// id is the ID for this status update
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// mediaId is the id of the media this status pertains too
	MediaId string               `protobuf:"bytes,2,opt,name=mediaId,proto3" json:"mediaId,omitempty"`
	Status  TelemetryStatusEntry `protobuf:"varint,3,opt,name=status,proto3,enum=api.TelemetryStatusEntry" json:"status,omitempty"`
	// Host this was started on
	Host                 string   `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TelemetryStatus) Reset()         { *m = TelemetryStatus{} }
func (m *TelemetryStatus) String() string { return proto.CompactTextString(m) }
func (*TelemetryStatus) ProtoMessage()    {}
func (*TelemetryStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a92aaa48c84f56, []int{1}
}

func (m *TelemetryStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TelemetryStatus.Unmarshal(m, b)
}
func (m *TelemetryStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TelemetryStatus.Marshal(b, m, deterministic)
}
func (m *TelemetryStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TelemetryStatus.Merge(m, src)
}
func (m *TelemetryStatus) XXX_Size() int {
	return xxx_messageInfo_TelemetryStatus.Size(m)
}
func (m *TelemetryStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_TelemetryStatus.DiscardUnknown(m)
}

var xxx_messageInfo_TelemetryStatus proto.InternalMessageInfo

func (m *TelemetryStatus) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TelemetryStatus) GetMediaId() string {
	if m != nil {
		return m.MediaId
	}
	return ""
}

func (m *TelemetryStatus) GetStatus() TelemetryStatusEntry {
	if m != nil {
		return m.Status
	}
	return TelemetryStatusEntry_EMPTY_4
}

func (m *TelemetryStatus) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

type TelemetryProgress struct {
	// id for this telemetry update
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// media id thjis perstains too
	MediaId string `protobuf:"bytes,2,opt,name=mediaId,proto3" json:"mediaId,omitempty"`
	// progress in 0-100
	Progress int32 `protobuf:"varint,3,opt,name=progress,proto3" json:"progress,omitempty"`
	// status
	Status TelemetryStatusEntry `protobuf:"varint,4,opt,name=status,proto3,enum=api.TelemetryStatusEntry" json:"status,omitempty"`
	// Host this was processed on
	Host                 string   `protobuf:"bytes,5,opt,name=host,proto3" json:"host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TelemetryProgress) Reset()         { *m = TelemetryProgress{} }
func (m *TelemetryProgress) String() string { return proto.CompactTextString(m) }
func (*TelemetryProgress) ProtoMessage()    {}
func (*TelemetryProgress) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a92aaa48c84f56, []int{2}
}

func (m *TelemetryProgress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TelemetryProgress.Unmarshal(m, b)
}
func (m *TelemetryProgress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TelemetryProgress.Marshal(b, m, deterministic)
}
func (m *TelemetryProgress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TelemetryProgress.Merge(m, src)
}
func (m *TelemetryProgress) XXX_Size() int {
	return xxx_messageInfo_TelemetryProgress.Size(m)
}
func (m *TelemetryProgress) XXX_DiscardUnknown() {
	xxx_messageInfo_TelemetryProgress.DiscardUnknown(m)
}

var xxx_messageInfo_TelemetryProgress proto.InternalMessageInfo

func (m *TelemetryProgress) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TelemetryProgress) GetMediaId() string {
	if m != nil {
		return m.MediaId
	}
	return ""
}

func (m *TelemetryProgress) GetProgress() int32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

func (m *TelemetryProgress) GetStatus() TelemetryStatusEntry {
	if m != nil {
		return m.Status
	}
	return TelemetryStatusEntry_EMPTY_4
}

func (m *TelemetryProgress) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func init() {
	proto.RegisterEnum("api.TelemetryStatusEntry", TelemetryStatusEntry_name, TelemetryStatusEntry_value)
	proto.RegisterType((*TelemetryError)(nil), "api.TelemetryError")
	proto.RegisterType((*TelemetryStatus)(nil), "api.TelemetryStatus")
	proto.RegisterType((*TelemetryProgress)(nil), "api.TelemetryProgress")
}

func init() { proto.RegisterFile("v1.telemetry.proto", fileDescriptor_c6a92aaa48c84f56) }

var fileDescriptor_c6a92aaa48c84f56 = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcd, 0x4a, 0xc3, 0x40,
	0x14, 0x85, 0xcd, 0x6f, 0xdb, 0x5b, 0x4d, 0xe3, 0xc5, 0x45, 0x74, 0x25, 0x59, 0x89, 0x8b, 0x40,
	0xd5, 0x17, 0x10, 0x67, 0x90, 0x42, 0x4d, 0xe2, 0x98, 0x28, 0x5d, 0x49, 0x24, 0x43, 0x0d, 0x58,
	0x13, 0x66, 0x46, 0xa1, 0x2e, 0x7d, 0x12, 0x1f, 0x55, 0x1c, 0x9b, 0x28, 0xe2, 0x26, 0xbb, 0x9c,
	0x7b, 0x72, 0x3e, 0xbe, 0xc5, 0x00, 0xbe, 0x4e, 0x23, 0xc5, 0x9f, 0xf8, 0x8a, 0x2b, 0xb1, 0x8e,
	0x1a, 0x51, 0xab, 0x1a, 0xad, 0xa2, 0xa9, 0xc2, 0x0c, 0xbc, 0xac, 0xbd, 0x53, 0x21, 0x6a, 0x81,
	0x1e, 0x98, 0x55, 0x19, 0x18, 0x87, 0xc6, 0xd1, 0x88, 0x99, 0x55, 0x89, 0x01, 0x0c, 0x56, 0xbc,
	0xac, 0x8a, 0x59, 0x19, 0x98, 0xfa, 0xd8, 0xc6, 0xef, 0x46, 0xca, 0x62, 0xc9, 0x03, 0xab, 0x6d,
	0x74, 0x0c, 0xdf, 0x0d, 0x98, 0x74, 0xd8, 0x1b, 0x55, 0xa8, 0x17, 0xd9, 0x83, 0x3b, 0x05, 0x57,
	0xea, 0x8d, 0xc6, 0x7a, 0x27, 0xfb, 0x51, 0xd1, 0x54, 0xd1, 0x1f, 0x1e, 0x7d, 0x56, 0x62, 0xcd,
	0x36, 0x3f, 0x22, 0x82, 0xfd, 0x58, 0x4b, 0x15, 0xd8, 0x9a, 0xa4, 0xbf, 0xc3, 0x0f, 0x03, 0x76,
	0xbb, 0x51, 0x2a, 0xea, 0xa5, 0xe0, 0xb2, 0x8f, 0xc6, 0x01, 0x0c, 0x9b, 0xcd, 0x4a, 0x8b, 0x38,
	0xac, 0xcb, 0xbf, 0x14, 0xed, 0xbe, 0x8a, 0xce, 0x8f, 0xe2, 0xf1, 0x1b, 0xec, 0xfd, 0xb7, 0xc1,
	0x31, 0x0c, 0xe8, 0x55, 0x9a, 0x2d, 0xee, 0xcf, 0xfc, 0x2d, 0x04, 0x70, 0xaf, 0x73, 0x9a, 0x53,
	0xe2, 0x1b, 0x38, 0x81, 0x31, 0x49, 0xee, 0xe2, 0x79, 0x72, 0x4e, 0x66, 0xf1, 0xa5, 0x6f, 0xa2,
	0x07, 0x70, 0x91, 0xc4, 0xb7, 0x94, 0x65, 0x5f, 0xd9, 0xc2, 0x1d, 0x18, 0xe5, 0x69, 0x5b, 0xdb,
	0xb8, 0x0d, 0x43, 0x42, 0xd3, 0x79, 0xb2, 0xa0, 0xc4, 0x77, 0x34, 0x96, 0xb1, 0x84, 0x51, 0xe2,
	0xbb, 0x0f, 0xae, 0x7e, 0x05, 0xa7, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xaf, 0x5e, 0x29, 0xbf,
	0x1b, 0x02, 0x00, 0x00,
}
